name: TFLint Check

on:
  push:
    branches:
      - main

jobs:
  print_access_key:
    runs-on: ubuntu-latest

    steps:
      - name: Set Access Key Environment Variable
        run: echo "ACCESS_KEY=$ACCESS_KEY" >> $GITHUB_ENV
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      
      - name: Print Access Key
        run: echo $ACCESS_KEY
  
  tflint_and_packer:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1
        with:
          tflint_version: "latest"  # Fetch the latest version of TFLint

      - name: Show Linux version
        run: uname -a


      - name: Run TFLint 
        run: tflint

