name: TFLint Check

on:
  push:
    branches:
      - main

jobs:
  tflint_and_packer:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1
        with:
          tflint_version: "latest"  # Fetch the latest version of TFLint

      - name: Run TFLint 
        run: tflint
